// events/events.js

export const EVENT_TYPES = {
  // ============ HR DEPARTMENT EVENTS ============
  HR_EMPLOYEE_ONBOARDED: "HR_EMPLOYEE_ONBOARDED",
  HR_EMPLOYEE_OFFBOARDED: "HR_EMPLOYEE_OFFBOARDED",
  HR_ROLE_ASSIGNED: "HR_ROLE_ASSIGNED",
  HR_ROLE_CHANGED: "HR_ROLE_CHANGED",
  HR_LEAVE_REQUESTED: "HR_LEAVE_REQUESTED",
  HR_LEAVE_APPROVED: "HR_LEAVE_APPROVED",
  HR_LEAVE_REJECTED: "HR_LEAVE_REJECTED",
  HR_PERFORMANCE_REVIEW_DUE: "HR_PERFORMANCE_REVIEW_DUE",
  HR_DOCUMENT_EXPIRING: "HR_DOCUMENT_EXPIRING",
  HR_BIRTHDAY_REMINDER: "HR_BIRTHDAY_REMINDER",
  HR_PROBATION_ENDING: "HR_PROBATION_ENDING",
  HR_CONTRACT_EXPIRING: "HR_CONTRACT_EXPIRING",

  // ============ FINANCE DEPARTMENT EVENTS ============
  FINANCE_SALARY_PROCESSED: "FINANCE_SALARY_PROCESSED",
  FINANCE_SALARY_PAID: "FINANCE_SALARY_PAID",
  FINANCE_SALARY_PENDING: "FINANCE_SALARY_PENDING",
  FINANCE_INVOICE_CREATED: "FINANCE_INVOICE_CREATED",
  FINANCE_INVOICE_OVERDUE: "FINANCE_INVOICE_OVERDUE",
  FINANCE_PAYMENT_RECEIVED: "FINANCE_PAYMENT_RECEIVED",
  FINANCE_EXPENSE_SUBMITTED: "FINANCE_EXPENSE_SUBMITTED",
  FINANCE_EXPENSE_APPROVED: "FINANCE_EXPENSE_APPROVED",
  FINANCE_BUDGET_EXCEEDED: "FINANCE_BUDGET_EXCEEDED",
  FINANCE_TRANSACTION_FLAGGED: "FINANCE_TRANSACTION_FLAGGED",
  FINANCE_MONTH_END_CLOSING: "FINANCE_MONTH_END_CLOSING",
  FINANCE_TAX_DEADLINE: "FINANCE_TAX_DEADLINE",
  FINANCE_AUDIT_SCHEDULED: "FINANCE_AUDIT_SCHEDULED",

  // ============ BUSINESS OPERATION EVENTS ============
  BIZ_ORDER_CREATED: "BIZ_ORDER_CREATED",
  BIZ_ORDER_CONFIRMED: "BIZ_ORDER_CONFIRMED",
  BIZ_ORDER_SHIPPED: "BIZ_ORDER_SHIPPED",
  BIZ_ORDER_DELIVERED: "BIZ_ORDER_DELIVERED",
  BIZ_ORDER_CANCELLED: "BIZ_ORDER_CANCELLED",
  BIZ_ORDER_RETURN_REQUESTED: "BIZ_ORDER_RETURN_REQUESTED",
  BIZ_ORDER_RETURN_EXPIRED: "BIZ_ORDER_RETURN_EXPIRED",
  BIZ_INVENTORY_LOW: "BIZ_INVENTORY_LOW",
  BIZ_INVENTORY_OUT: "BIZ_INVENTORY_OUT",
  BIZ_SUPPLIER_PAYMENT_DUE: "BIZ_SUPPLIER_PAYMENT_DUE",
  BIZ_CUSTOMER_COMPLAINT: "BIZ_CUSTOMER_COMPLAINT",
  BIZ_QUALITY_ISSUE: "BIZ_QUALITY_ISSUE",
  BIZ_SHIPMENT_DELAYED: "BIZ_SHIPMENT_DELAYED",

  // ============ CROSS-DEPARTMENT EVENTS ============
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  SYSTEM_UPDATE: "SYSTEM_UPDATE",
  SYSTEM_ALERT: "SYSTEM_ALERT",
  MEETING_SCHEDULED: "MEETING_SCHEDULED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_COMPLETED: "TASK_COMPLETED",
  DEADLINE_APPROACHING: "DEADLINE_APPROACHING",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
};

// Map events to departments
export const EVENT_DEPARTMENT_MAP = {
  // HR Events
  HR_EMPLOYEE_ONBOARDED: "HR",
  HR_EMPLOYEE_OFFBOARDED: "HR",
  HR_ROLE_ASSIGNED: "HR",
  HR_ROLE_CHANGED: "HR",
  HR_LEAVE_REQUESTED: "HR",
  HR_LEAVE_APPROVED: "HR",
  HR_LEAVE_REJECTED: "HR",
  HR_PERFORMANCE_REVIEW_DUE: "HR",
  HR_DOCUMENT_EXPIRING: "HR",
  HR_BIRTHDAY_REMINDER: "HR",
  HR_PROBATION_ENDING: "HR",
  HR_CONTRACT_EXPIRING: "HR",

  // Finance Events
  FINANCE_SALARY_PROCESSED: "Finance",
  FINANCE_SALARY_PAID: "Finance",
  FINANCE_SALARY_PENDING: "Finance",
  FINANCE_INVOICE_CREATED: "Finance",
  FINANCE_INVOICE_OVERDUE: "Finance",
  FINANCE_PAYMENT_RECEIVED: "Finance",
  FINANCE_EXPENSE_SUBMITTED: "Finance",
  FINANCE_EXPENSE_APPROVED: "Finance",
  FINANCE_BUDGET_EXCEEDED: "Finance",
  FINANCE_TRANSACTION_FLAGGED: "Finance",
  FINANCE_MONTH_END_CLOSING: "Finance",
  FINANCE_TAX_DEADLINE: "Finance",
  FINANCE_AUDIT_SCHEDULED: "Finance",

  // Business Operation Events
  BIZ_ORDER_CREATED: "BusinessOperation",
  BIZ_ORDER_CONFIRMED: "BusinessOperation",
  BIZ_ORDER_SHIPPED: "BusinessOperation",
  BIZ_ORDER_DELIVERED: "BusinessOperation",
  BIZ_ORDER_CANCELLED: "BusinessOperation",
  BIZ_ORDER_RETURN_REQUESTED: "BusinessOperation",
  BIZ_ORDER_RETURN_EXPIRED: "BusinessOperation",
  BIZ_INVENTORY_LOW: "BusinessOperation",
  BIZ_INVENTORY_OUT: "BusinessOperation",
  BIZ_SUPPLIER_PAYMENT_DUE: "BusinessOperation",
  BIZ_CUSTOMER_COMPLAINT: "BusinessOperation",
  BIZ_QUALITY_ISSUE: "BusinessOperation",
  BIZ_SHIPMENT_DELAYED: "BusinessOperation",

  // Cross-department (can be sent to any department)
  SYSTEM_MAINTENANCE: "ALL",
  SYSTEM_UPDATE: "ALL",
  SYSTEM_ALERT: "ALL",
  MEETING_SCHEDULED: "ALL",
  TASK_ASSIGNED: "ALL",
  TASK_COMPLETED: "ALL",
  DEADLINE_APPROACHING: "ALL",
  APPROVAL_REQUIRED: "ALL",
};

// Event priority levels
export const EVENT_PRIORITIES = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
  CRITICAL: "critical",
};

// Helper to get department from event type
export const getDepartmentFromEvent = (eventType) => {
  return EVENT_DEPARTMENT_MAP[eventType] || "ALL";
};