import mongoose from "mongoose";

const roleSchema = new mongoose.Schema(
  {
    employeeId: {
      type: String, // or ObjectId if referencing Employee collection. Database refrence
      required: true,
    },
    autoGeneratedId: {
      type: String, // used for login, saving credentials.
    },
    employeeName: {
      type: String,
    },
    role: {
      office: { type: String, required: true },
      group: { type: String,  },
      division: { type: String, },
      department: { type: String,  },
      branch: { type: String,  },
      cell: { type: String,  },
      desk: { type: String }
    },
  },
  {
    timestamps: true,
  }
);

const RoleModel = mongoose.model("Role", roleSchema);
export default RoleModel;
