
export const CONSTANTS = {
  // ==================== DEPARTMENTS ====================
  DEPARTMENTS: {
    HR: 'HR',
    FINANCE: 'Finance',
    BUSINESS_OPERATION: 'BusinessOperation',
    IT: 'IT',
    COMPLIANCE: 'Compliance',
    ALL: 'All'
  },

  // ==================== ORG UNIT TYPES ====================
  ORG_UNIT_TYPES: {
    ORG_ROOT: 'ORG_ROOT',
    BOARD: 'BOARD',
    EXECUTIVE: 'EXECUTIVE',
    DIVISION: 'DIVISION',
    DEPARTMENT: 'DEPARTMENT',
    DESK: 'DESK',
    CELL: 'CELL'
  },

  // ==================== HIERARCHY SCOPES ====================
  HIERARCHY_SCOPES: {
    SELF: 'SELF',
    DESCENDANT: 'DESCENDANT',
    DEPARTMENT: 'DEPARTMENT',
    ORGANIZATION: 'ORGANIZATION'
  },

  // ==================== ACTION TYPES ====================
  ACTION_TYPES: {
    ADMINISTRATIVE: 'ADMINISTRATIVE',
    FUNCTIONAL: 'FUNCTIONAL',
    INFORMATIONAL: 'INFORMATIONAL'
  },

  // ==================== RESOURCE TYPES ====================
  RESOURCE_TYPES: {
    EMPLOYEE: 'EMPLOYEE',
    LEAVE: 'LEAVE',
    ROLE: 'ROLE',
    PERMISSION: 'PERMISSION',
    ORG_UNIT: 'ORG_UNIT',
    SALARY: 'SALARY',
    LEDGER: 'LEDGER',
    EXPENSE: 'EXPENSE',
    COMMISSION: 'COMMISSION',
    ALL: 'ALL'
  },

  // ==================== EXECUTIVE LEVELS ====================
  EXECUTIVE_LEVELS: [0, 1, 2], // Chairman, Board, CEO

  // ==================== POWER RANK THRESHOLDS ====================
  POWER_RANKS: {
    SUPREME: 0,
    EXECUTIVE: 1,
    SENIOR: 2,
    MANAGEMENT: 3,
    SUPERVISORY: 4,
    OPERATIONAL: 5,
    INDIVIDUAL: 6
  },

  // ==================== AUDIT EVENTS ====================
  AUDIT_EVENTS: {
    // HR events
    EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
    EMPLOYEE_SUBMITTED: 'EMPLOYEE_SUBMITTED',
    EMPLOYEE_APPROVED: 'EMPLOYEE_APPROVED',
    EMPLOYEE_REJECTED: 'EMPLOYEE_REJECTED',
    EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
    EMPLOYEE_DELETED: 'EMPLOYEE_DELETED',
    EMPLOYEE_BLOCKED: 'EMPLOYEE_BLOCKED',
    EMPLOYEE_SUSPENDED: 'EMPLOYEE_SUSPENDED',
    EMPLOYEE_TERMINATED: 'EMPLOYEE_TERMINATED',
    EMPLOYEE_RESTORED: 'EMPLOYEE_RESTORED',
    DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
    DOCUMENT_REVIEWED: 'DOCUMENT_REVIEWED',
    DOCUMENT_DELETED: 'DOCUMENT_DELETED',
    ROLE_CREATED: 'ROLE_CREATED',
    ROLE_UPDATED: 'ROLE_UPDATED',
    ROLE_DELETED: 'ROLE_DELETED',
    ROLE_ASSIGNED: 'ROLE_ASSIGNED',
    PERMISSION_MODIFIED: 'PERMISSION_MODIFIED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    ORGUNIT_CREATED: 'ORGUNIT_CREATED',
    ORGUNIT_UPDATED: 'ORGUNIT_UPDATED',
    ORGUNIT_DELETED: 'ORGUNIT_DELETED',
    ORGUNIT_MOVED: 'ORGUNIT_MOVED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    PASSWORD_RESET: 'PASSWORD_RESET',
    TOKEN_REFRESHED: 'TOKEN_REFRESHED',
    HIERARCHY_VIOLATION: 'HIERARCHY_VIOLATION',
    DEPARTMENT_VIOLATION: 'DEPARTMENT_VIOLATION',

    // Financial events
    JOURNAL_POSTED: 'JOURNAL_POSTED',
    BALANCE_UPDATED: 'BALANCE_UPDATED',
    COMMISSION_REPORT_CREATED: 'COMMISSION_REPORT_CREATED',
    COMMISSION_SETTLED: 'COMMISSION_SETTLED',
    EXPENSE_REPORT_CREATED: 'EXPENSE_REPORT_CREATED',
    EXPENSE_PAID: 'EXPENSE_PAID',
    SALARY_BREAKUP_CREATED: 'SALARY_BREAKUP_CREATED',
  },

  // ==================== HR & FINANCIAL EVENT ENUMS ====================
  HR_AUDIT_EVENTS: [
    "EMPLOYEE_CREATED", "EMPLOYEE_SUBMITTED", "EMPLOYEE_APPROVED", "EMPLOYEE_REJECTED",
    "EMPLOYEE_UPDATED", "EMPLOYEE_DELETED", "EMPLOYEE_BLOCKED", "EMPLOYEE_SUSPENDED",
    "EMPLOYEE_TERMINATED", "EMPLOYEE_RESTORED", "DOCUMENT_UPLOADED", "DOCUMENT_REVIEWED",
    "DOCUMENT_DELETED", "ROLE_CREATED", "ROLE_UPDATED", "ROLE_DELETED", "ROLE_ASSIGNED",
    "PERMISSION_MODIFIED", "PERMISSION_DENIED", "ORGUNIT_CREATED", "ORGUNIT_UPDATED",
    "ORGUNIT_DELETED", "ORGUNIT_MOVED", "LOGIN_SUCCESS", "LOGIN_FAILED", "LOGOUT",
    "PASSWORD_RESET", "TOKEN_REFRESHED", "HIERARCHY_VIOLATION", "DEPARTMENT_VIOLATION"
  ],

  FINANCIAL_AUDIT_EVENTS: [
    "JOURNAL_POSTED", "BALANCE_UPDATED", "COMMISSION_REPORT_CREATED",
    "COMMISSION_SETTLED", "EXPENSE_REPORT_CREATED", "EXPENSE_PAID", "SALARY_BREAKUP_CREATED"
  ],

  // ==================== CACHE TTL ====================
  CACHE_TTL: {
    PERMISSIONS: 300,
    HIERARCHY: 600,
    ORG_STRUCTURE: 1800
  }
};

// ==================== HELPER FUNCTIONS ====================

/**
 * Check if department code is valid
 */
export function isValidDepartment(code) {
  return Object.values(CONSTANTS.DEPARTMENTS).includes(code);
}

/**
 * Check if user is at executive level
 */
export function isExecutiveLevel(level) {
  return CONSTANTS.EXECUTIVE_LEVELS.includes(level);
}

/**
 * Get all department codes
 */
export function getAllDepartments() {
  return Object.values(CONSTANTS.DEPARTMENTS);
}

/**
 * Check if department is executive (ALL)
 */
export function isExecutiveDepartment(code) {
  return code === CONSTANTS.DEPARTMENTS.ALL;
}

/**
 * Get power rank description
 */
export function getPowerRankName(level) {
  const ranks = Object.entries(CONSTANTS.POWER_RANKS);
  const rank = ranks.find(([_, value]) => value === level);
  return rank ? rank[0] : 'UNKNOWN';
}

export default CONSTANTS;